#!/usr/bin/env sh
. "$(dirname -- "$0")/husky.sh"

# Função para exibir mensagens de erro
error_exit() {
    echo "Erro: $1"
    exit 1
}

# rodar os testes
php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉";
    exit 1;
fi;

# Formatar cada arquivo alterado usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

echo "Todos os testes passaram e os arquivos foram formatados com sucesso!"
